"""
Executor Manager — Master Controller for Part 3 (Data Trade & Execution)
==========================================================================
Coordinates the entire lifecycle of trade decision-making and execution:
1. Risk & Money Management Gating
2. AI Decision Analysis (DeepSeek Browser Agent / Gemini API)
3. Decision Schema & Threshold Validation
4. Trading Mode Enforcement (AI SIGNAL_BOT vs AI AUTO_BOT)
5. Binary Option Broker Order Execution
6. Asynchronous Trade Settlement & History Tracking
"""

import os
import logging
import traceback
from typing import Dict, Any, Optional

from config_setting.config_loader import load_settings
from data_trade.ai_decision.system_prompt import SystemPrompt
from data_trade.ai_decision.ai_deepseek_browser import DeepSeekBrowserAgent
from data_trade.ai_decision.ai_gemini_api import GeminiApiAgent
from data_trade.execution_gate.gate_controller import ExecutionGate
from data_trade.execution_gate.money_manager import MoneyManager
from data_trade.execution_gate.broker_executor import BrokerExecutor
from data_trade.execution_gate.order_tracker import OrderTracker

logger = logging.getLogger("ExecutorManager")


class ExecutorManager:
    """Central entry point for Part 3 trade decision and execution pipeline."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.settings = config or load_settings(reload=False)
        self.execution_gate = ExecutionGate(config=self.settings)
        self.money_manager = MoneyManager(config=self.settings)
        self.broker_executor = BrokerExecutor()
        self.order_tracker = OrderTracker(money_manager=self.money_manager)

        # ── Initialize Modular AI Agent ──────────────────────────────────────
        ai_cfg = self.settings.get("ai_mode", {})
        self.ai_enabled = bool(ai_cfg.get("enabled", True))
        self.primary_engine = str(ai_cfg.get("primary_engine", "deepseek")).lower()

        if not self.ai_enabled:
            self.ai_agent = None
            logger.info("[ExecutorManager] AI Mode is disabled in settings.json")
        elif self.primary_engine == "gemini":
            gemini_model = ai_cfg.get("gemini_model", "gemini-2.5-flash")
            self.ai_agent = GeminiApiAgent(model_name=gemini_model)
            logger.info(f"[ExecutorManager] Initialized Gemini API Agent ({gemini_model})")
        else:
            session_idx = int(ai_cfg.get("deepseek_session_index", 1))
            self.ai_agent = DeepSeekBrowserAgent(session_id=session_idx)
            logger.info(f"[ExecutorManager] Initialized DeepSeek Browser Agent (Session {session_idx})")

        # ── Trading Mode ────────────────────────────────────────────────────
        self.trading_mode = str(self.settings.get("account", {}).get("trading_mode", "AI AUTO_BOT")).strip().upper()
        logger.info(f"[ExecutorManager] Active Trading Mode: '{self.trading_mode}'")

    def process_cycle_decision(
        self,
        symbol: str,
        prompt_filepath: str,
        payload: Optional[Dict[str, Any]] = None,
        broker_adapter: Optional[Any] = None
    ) -> Dict[str, Any]:
        """
        Executes complete Part 3 workflow for an asset cycle.
        
        Args:
            symbol: Target asset symbol.
            prompt_filepath: Path to the 100-line prompt generated by Part 2.
            payload: Full analysis payload from Part 2.
            broker_adapter: Active broker connection instance.
            
        Returns:
            Complete execution summary dictionary.
        """
        if not symbol or not isinstance(symbol, str):
            raise ValueError("FAIL-FAST: symbol must be a non-empty string")
        if not prompt_filepath or not isinstance(prompt_filepath, str):
            raise ValueError("FAIL-FAST: prompt_filepath must be a non-empty string")

        logger.info(f"[ExecutorManager] Starting Part 3 decision flow for {symbol} (Prompt: {prompt_filepath})")

        # ── Step 1: Pre-Trade Risk Gate (MoneyManager) ──────────────────────
        can_trade, risk_reason = self.money_manager.can_trade()
        if not can_trade:
            logger.info(f"[ExecutorManager] {symbol} skipped: Risk limit active ({risk_reason})")
            return {
                "symbol": symbol,
                "action": "BLOCKED_BY_RISK",
                "reason": risk_reason,
                "order_executed": False,
                "order_data": None,
                "ai_decision": None,
                "risk_status": self.money_manager.get_risk_status()
            }

        # ── Step 2: Read Prompt Content & Dispatch to AI Agent ──────────────
        if not os.path.exists(prompt_filepath):
            raise FileNotFoundError(f"FAIL-FAST: Prompt file not found at {prompt_filepath}")

        with open(prompt_filepath, "r", encoding="utf-8") as f:
            prompt_content = f.read().strip()

        if not prompt_content:
            raise ValueError(f"FAIL-FAST: Prompt file {prompt_filepath} is empty")

        if self.ai_agent is None:
            ai_decision = {
                "symbol": symbol,
                "action": "WAIT",
                "expiry_minutes": 1,
                "confidence_score": 0,
                "reason_th": "AI Mode ถูกปิดใช้งานใน settings.json",
                "engine_used": "DISABLED"
            }
        else:
            try:
                ai_decision = SystemPrompt.process_ai_decision(
                    symbol=symbol,
                    payload_text=prompt_content,
                    ai_agent=self.ai_agent
                )
            except Exception as e:
                logger.exception(f"[ExecutorManager] AI analysis failed for {symbol}: {e}")
                traceback.print_exc()
                raise RuntimeError(f"FAIL-FAST: AI analysis failed for {symbol}: {e}") from e

        # ── Step 3: Execution Gate (The Single Decisive Authority) ──────────
        try:
            gate_verdict = self.execution_gate.evaluate_decision(
                symbol=symbol,
                ai_decision=ai_decision,
                payload=payload
            )
        except Exception as e:
            logger.exception(f"[ExecutorManager] Execution Gate evaluation failed for {symbol}: {e}")
            traceback.print_exc()
            raise RuntimeError(f"FAIL-FAST: Execution Gate evaluation failed for {symbol}: {e}") from e

        # ── Step 4: Trading Mode Enforcement (AI SIGNAL_BOT vs AI AUTO_BOT) ─
        should_execute_order = bool(gate_verdict.get("approved", False))

        if self.trading_mode == "AI SIGNAL_BOT":
            should_execute_order = False
            logger.info(
                f"[ExecutorManager] [MODE: AI SIGNAL_BOT] Signal for {symbol}: "
                f"Action={gate_verdict.get('action')}, "
                f"Confidence={gate_verdict.get('confidence_score')}%, "
                f"Expiry={gate_verdict.get('expiry_minutes')}m, "
                f"Reason={gate_verdict.get('reason')}"
            )

        # ── Step 5: Broker Order Execution (if Approved and AUTO_BOT) ───────
        order_data = None
        if should_execute_order:
            action = gate_verdict["action"]
            expiry_minutes = gate_verdict["expiry_minutes"]
            stake = self.money_manager.get_stake(symbol)

            if broker_adapter is None:
                logger.warning(f"[ExecutorManager] No broker_adapter provided — simulated execution for {symbol}")
                order_data = {
                    "status": "SIMULATED",
                    "order_id": "SIM_ORDER_001",
                    "symbol": symbol,
                    "action": action,
                    "stake": stake,
                    "expiry_minutes": expiry_minutes
                }
            else:
                try:
                    order_data = self.broker_executor.execute_order(
                        symbol=symbol,
                        action=action,
                        expiry_minutes=expiry_minutes,
                        stake=stake,
                        broker_adapter=broker_adapter
                    )
                    
                    # ── Asynchronous Order Tracking ─────────────────────────
                    if order_data.get("status") == "SUCCESS":
                        self.order_tracker.track_order(
                            order_data=order_data,
                            ai_decision=ai_decision,
                            broker_adapter=broker_adapter
                        )
                except Exception as e:
                    logger.exception(f"[ExecutorManager] Broker execution failed for {symbol}: {e}")
                    traceback.print_exc()
                    raise

        # ── Step 6: Update Part 2 Payload AI Fields (Part 2 to Part 3 Handover) ──
        if payload and isinstance(payload, dict):
            core = payload.get("core_analysis", {})
            if isinstance(core, dict):
                core["dl_confidence_score"] = gate_verdict.get("confidence_score", 0)
                core["dl_suggested_expiry_minutes"] = gate_verdict.get("expiry_minutes", 1)
                core["dl_suggested_action"] = gate_verdict.get("action", "WAIT")
                core["dl_final_reason_th"] = gate_verdict.get("reason", "")

        return {
            "symbol": symbol,
            "action": gate_verdict.get("action", "WAIT"),
            "expiry_minutes": gate_verdict.get("expiry_minutes", 1),
            "confidence_score": gate_verdict.get("confidence_score", 0),
            "reason": gate_verdict.get("reason", ""),
            "should_execute": should_execute_order,
            "order_executed": (order_data is not None and order_data.get("status") == "SUCCESS"),
            "order_data": order_data,
            "ai_decision": ai_decision,
            "risk_status": self.money_manager.get_risk_status()
        }
